[ENV]
active_env = test
#test测试环境

[test]
api_host = https://user.360lj.com
ui_url = https://user.360lj.com

[pre]
api_host = https://user-pre.360lj.com
ui_url = https://user-pre.360lj.com

[prod]
api_host = https://user.360lj.com
ui_url = https://user.360lj.com